# Generated by Django 5.2 on 2025-04-12 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, verbose_name='Placa')),
                ('entrada', models.DateTimeField(auto_now_add=True, verbose_name='Horário de Entrada')),
                ('saida', models.DateTimeField(blank=True, null=True, verbose_name='Horário de Saída')),
                ('pago', models.BooleanField(default=False, verbose_name='Pagamento Realizado')),
            ],
        ),
    ]
