# Generated by Django 5.2 on 2025-04-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking_systems', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor a Pagar'),
        ),
    ]
